title: Sahipkıran
description: Minyatür Savaş Oyunu Kuralları
theme: just-the-docs

url: 

aux_links:
  İndir: https://hexhunt.itch.io/sahipkiran

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust
markup / liquid-based content.
footer_content: "Sahipkıran, <a href=\"https://creativecommons.org/licenses/by-nc-sa/4.0/deed.tr">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International</a> lisansı altında yayımlanmıştır."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


